'use client';

/**
 * /site/[bizId] — the public landing page generated by the AI studio.
 * Premium, branded, mobile-first; CTA drives to the booking page.
 */

import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import { Box, Typography, Button, CircularProgress } from '@mui/material';

interface LandingData {
  landing: Record<string, unknown>;
  bizName: string; logo: string; accent: string; phone: string;
}

export default function SitePage() {
  const params = useParams();
  const bizId = String(params?.id || '');
  const [data, setData] = useState<LandingData | null>(null);
  const [err, setErr] = useState(false);

  useEffect(() => {
    if (!bizId) return;
    fetch(`/api/landing?bizId=${bizId}`).then((r) => r.ok ? r.json() : Promise.reject()).then(setData).catch(() => setErr(true));
  }, [bizId]);

  if (err) return <Box sx={{ minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', bgcolor: '#FAFAF9' }}><Typography sx={{ color: '#78716C' }}>הדף לא נמצא 🤔</Typography></Box>;
  if (!data) return <Box sx={{ minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', bgcolor: '#FAFAF9' }}><CircularProgress /></Box>;

  const L = data.landing as { heroTitle?: string; heroSubtitle?: string; ctaText?: string; about?: string; services?: Array<{ name?: string; description?: string; price?: string } | string>; ctaSection?: string };
  const accent = data.accent;
  const bookUrl = `/book/${bizId}`;
  const waPhone = data.phone.replace(/\D/g, '').replace(/^0/, '972');

  return (
    <Box sx={{ minHeight: '100vh', bgcolor: '#FFFFFF', fontFamily: 'inherit' }}>
      {/* Hero */}
      <Box sx={{ background: `linear-gradient(160deg, ${accent} 0%, ${accent}CC 60%, ${accent}99 100%)`, color: '#fff', textAlign: 'center', px: 3, pt: 8, pb: 9, position: 'relative', overflow: 'hidden' }}>
        <Box sx={{ position: 'absolute', top: -60, right: -40, width: 220, height: 220, borderRadius: '50%', bgcolor: 'rgba(255,255,255,0.1)' }} />
        <Box sx={{ position: 'absolute', bottom: -80, left: -50, width: 260, height: 260, borderRadius: '50%', bgcolor: 'rgba(255,255,255,0.08)' }} />
        {data.logo && <Box component="img" src={data.logo} alt="" sx={{ width: 84, height: 84, borderRadius: 3, objectFit: 'cover', mb: 2.5, boxShadow: '0 12px 32px rgba(0,0,0,0.25)', position: 'relative' }} />}
        <Typography sx={{ fontSize: { xs: 34, sm: 46 }, fontWeight: 900, letterSpacing: '-0.03em', lineHeight: 1.1, position: 'relative' }}>{L.heroTitle || data.bizName}</Typography>
        {L.heroSubtitle && <Typography sx={{ fontSize: 17, opacity: 0.92, mt: 1.5, maxWidth: 520, mx: 'auto', lineHeight: 1.6, position: 'relative' }}>{L.heroSubtitle}</Typography>}
        <Button href={bookUrl} sx={{ mt: 3.5, bgcolor: '#fff', color: accent, fontWeight: 900, fontSize: 16, px: 5, py: 1.6, borderRadius: 99, boxShadow: '0 12px 30px rgba(0,0,0,0.2)', position: 'relative', '&:hover': { bgcolor: '#fff', transform: 'translateY(-2px)' }, transition: 'all 0.2s' }}>
          {L.ctaText || 'קביעת תור אונליין'} ←
        </Button>
      </Box>

      <Box sx={{ maxWidth: 620, mx: 'auto', px: 3 }}>
        {/* About */}
        {L.about && (
          <Box sx={{ py: 5, textAlign: 'center' }}>
            <Typography sx={{ fontSize: 13, fontWeight: 800, color: accent, letterSpacing: '0.1em', mb: 1.5 }}>קצת עלינו</Typography>
            <Typography sx={{ fontSize: 16, color: '#44403C', lineHeight: 1.9 }}>{L.about}</Typography>
          </Box>
        )}

        {/* Services */}
        {Array.isArray(L.services) && L.services.length > 0 && (
          <Box sx={{ pb: 5 }}>
            <Typography sx={{ fontSize: 13, fontWeight: 800, color: accent, letterSpacing: '0.1em', mb: 2, textAlign: 'center' }}>השירותים שלנו</Typography>
            <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1.25 }}>
              {L.services.slice(0, 8).map((s, i) => {
                const item = typeof s === 'string' ? { name: s } : s;
                return (
                  <Box key={i} sx={{ display: 'flex', alignItems: 'center', gap: 2, border: '1px solid #E7E5E4', borderRadius: 3, p: 2.25, transition: 'all 0.15s', '&:hover': { borderColor: accent, boxShadow: '0 6px 18px rgba(0,0,0,0.05)' } }}>
                    <Box sx={{ width: 10, height: 10, borderRadius: '50%', bgcolor: accent, flexShrink: 0 }} />
                    <Box sx={{ flex: 1 }}>
                      <Typography sx={{ fontSize: 15.5, fontWeight: 800, color: '#1C1917' }}>{item.name}</Typography>
                      {item.description && <Typography sx={{ fontSize: 13, color: '#78716C', mt: 0.25 }}>{item.description}</Typography>}
                    </Box>
                    {item.price && <Typography sx={{ fontSize: 15, fontWeight: 900, color: accent }}>{item.price}</Typography>}
                  </Box>
                );
              })}
            </Box>
          </Box>
        )}

        {/* CTA section */}
        <Box sx={{ bgcolor: '#FAFAF9', border: '1px solid #E7E5E4', borderRadius: 4, p: 4, textAlign: 'center', mb: 6 }}>
          <Typography sx={{ fontSize: 20, fontWeight: 900, color: '#1C1917', mb: 2, lineHeight: 1.4 }}>{L.ctaSection || 'מחכים לראות אתכם!'}</Typography>
          <Box sx={{ display: 'flex', gap: 1.25, justifyContent: 'center', flexWrap: 'wrap' }}>
            <Button href={bookUrl} sx={{ bgcolor: accent, color: '#fff', fontWeight: 800, px: 4, py: 1.4, borderRadius: 99, '&:hover': { bgcolor: accent, opacity: 0.9 } }}>📅 {L.ctaText || 'קביעת תור'}</Button>
            {data.phone && <Button href={`tel:${data.phone}`} sx={{ border: `2px solid ${accent}`, color: accent, fontWeight: 800, px: 3, py: 1.2, borderRadius: 99 }}>📞 התקשרו</Button>}
            {waPhone && <Button href={`https://wa.me/${waPhone}`} target="_blank" sx={{ border: '2px solid #25D366', color: '#1EA952', fontWeight: 800, px: 3, py: 1.2, borderRadius: 99 }}>💬 וואטסאפ</Button>}
          </Box>
        </Box>

        <Typography sx={{ textAlign: 'center', pb: 4, fontSize: 11.5, color: '#C4BDB4' }}>נבנה עם Zikkit 💜</Typography>
      </Box>
    </Box>
  );
}
